name: Build & Deploy Javadoc

on:
  push:
    branches: [ main, master, ci-test ]
    paths: ["src/main/java/fyi/taf/PersonalTax/**", "src/test/java/fyi/taf/PersonalTax/**", ".github/workflows/doc.yml", "pom.xml"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Javadoc
        run: mvn site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site