name: Test & Build (& Release)

on:
  push:
    branches: [ main, master, ci-test ]
    paths: ["src/main/java/fyi/taf/PersonalTax/**", "src/test/java/fyi/taf/PersonalTax/**", "pom.xml"]

jobs:
  test-and-build:
    name: "Test & Build - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            package-type: deb
            suffix: ""
          - os: windows-latest
            package-type: msi
            suffix: ".exe"
          - os: macos-latest
            package-type: pkg
            suffix: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Extract & validate project version
      shell: bash
      id: extract-and-validate-version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/\r$//')
        
        VERSION=$(echo $VERSION | tr -d '\n')
        
        echo "VERSION=$VERSION" >> $GITHUB_ENV

        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?$ ]]; then
          echo "::error::Invalid version format: $VERSION"
          exit 1
        fi

    - name: Test and then build jar
      run: mvn clean package

    - name: Build Executable
      shell: bash
      run: |
        case ${{ matrix.os }} in
          ubuntu-latest)
            jpackage --input target/ \
              --name PersonalTax \
              --main-jar PersonalTax-${{ env.VERSION }}.jar \
              --type ${{ matrix.package-type }} \
              --dest release
            ;;
          windows-latest)
            jpackage --input target/ \
              --name PersonalTax \
              --main-jar PersonalTax-${{ env.VERSION }}.jar \
              --type ${{ matrix.package-type }} \
              --win-console \
              --dest release
            ;;
          macos-latest)
            jpackage --input target/ \
              --name PersonalTax \
              --main-jar PersonalTax-${{ env.VERSION }}.jar \
              --type ${{ matrix.package-type }} \
              --dest release
            ;;
        esac

    - name: Upload Artifact (Only for tags)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          release/*
          target/PersonalTax-${{ env.VERSION }}.jar

  release:
    name: Create Release
    needs: test-and-build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        body: |
          Auto-generated release for version ${{ github.ref_name }}
          Files:
          - Windows Installer (.msi)
          - Linux Package (.deb)
          - macOS Package (.pkg)
          - Cross-platform JAR file
        files: |
          artifacts/**/*
